# Generated by Django 5.2.10 on 2026-02-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chafon_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ware',
            name='kategorie',
        ),
        migrations.AddField(
            model_name='ware',
            name='kategorien',
            field=models.ManyToManyField(blank=True, related_name='waren', to='chafon_api.warenkategorie'),
        ),
    ]
