# Generated by Django 5.2.10 on 2026-02-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chafon_api', '0002_ware_multiple_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warenkategorie',
            name='qualifikation_erforderlich',
        ),
        migrations.AddField(
            model_name='warenkategorie',
            name='minimale_rolle',
            field=models.CharField(choices=[('Student', 'Student'), ('Mitarbeiter', 'Mitarbeiter'), ('Laborleiter', 'Laborleiter'), ('Admin', 'Admin')], default='Student', max_length=20),
        ),
    ]
