# Generated by Django 5.2.10 on 2026-02-27 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chafon_api', '0003_add_minimale_rolle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbleibOrt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('beschreibung', models.TextField(blank=True)),
                ('reihenfolge', models.IntegerField(default=0)),
                ('aktiv', models.BooleanField(default=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Verbleib Orte',
                'ordering': ['reihenfolge', 'name'],
                'indexes': [models.Index(fields=['aktiv', 'reihenfolge'], name='chafon_api__aktiv_bad584_idx')],
            },
        ),
        migrations.AddField(
            model_name='warenkategorie',
            name='gesperrte_verbleib_orte',
            field=models.ManyToManyField(blank=True, related_name='gesperrt_fuer_kategorien', to='chafon_api.verbleibort'),
        ),
    ]
