# Generated by Django 5.2.10 on 2026-03-03 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chafon_api', '0004_add_verbleib_orte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErlaubteEmailDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(help_text='z.B. @th-koeln.de oder @smail.th-koeln.de', max_length=100, unique=True)),
                ('beschreibung', models.CharField(blank=True, help_text='Optional: Beschreibung der Domain', max_length=255)),
                ('aktiv', models.BooleanField(default=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Erlaubte E-Mail Domains',
                'ordering': ['domain'],
            },
        ),
    ]
