# Generated by Django 5.2.10 on 2026-03-03 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chafon_api', '0005_add_email_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategorieVerbleibRegel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimale_rolle', models.CharField(choices=[('Student', 'Student'), ('Mitarbeiter', 'Mitarbeiter'), ('Laborleiter', 'Laborleiter'), ('Admin', 'Admin')], default='Student', max_length=20)),
                ('gesperrt', models.BooleanField(default=False)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbleib_regeln', to='chafon_api.warenkategorie')),
                ('verbleib_ort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategorie_regeln', to='chafon_api.verbleibort')),
            ],
            options={
                'verbose_name_plural': 'Kategorie-Verbleib Regeln',
                'indexes': [models.Index(fields=['kategorie', 'verbleib_ort'], name='chafon_api__kategor_7061d5_idx')],
                'constraints': [models.UniqueConstraint(fields=('kategorie', 'verbleib_ort'), name='unique_kategorie_verbleib')],
            },
        ),
    ]
