# Generated by Django 5.2.10 on 2026-03-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chafon_api', '0006_kategorieverbleibregel'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ware',
            name='chafon_api__aktiv_d4a729_idx',
        ),
        migrations.RemoveField(
            model_name='ware',
            name='ist_ausleihbar',
        ),
    ]
