# Generated by Django 5.2.10 on 2026-03-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chafon_api', '0007_remove_ware_chafon_api__aktiv_d4a729_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbleibort',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='warenkategorie',
            constraint=models.UniqueConstraint(condition=models.Q(('aktiv', True)), fields=('name',), name='unique_name_when_active'),
        ),
    ]
