# Generated by Django 5.2.10 on 2026-03-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chafon_api', '0009_alter_warenkategorie_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbleibort',
            name='raumnummer_erforderlich',
            field=models.BooleanField(default=False),
        ),
    ]
