# Generated by Django 5.2.10 on 2026-03-09 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chafon_api', '0010_add_raumnummer_erforderlich_to_verbleibort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schadensmeldung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beschreibung', models.TextField(help_text='Beschreibung des Schadens')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('quittiert', models.BooleanField(default=False, help_text='Wurde die Meldung vom Mitarbeiter quittiert?')),
                ('quittiert_am', models.DateTimeField(blank=True, null=True)),
                ('quittierer_beschreibung', models.TextField(blank=True, help_text='Ergänzende Beschreibung durch Quittierer')),
                ('ausleihe', models.ForeignKey(blank=True, help_text='Verknüpfung zur Ausleihe (nur bei Rückgabe)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schadensmeldungen', to='chafon_api.ausleihe')),
                ('quittierer', models.ForeignKey(blank=True, help_text='Mitarbeiter der quittiert hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quittierte_schadensmeldungen', to='chafon_api.benutzer')),
                ('rueckgeber', models.ForeignKey(blank=True, help_text='Wer hat die Meldung erstellt (Student bei Rückgabe)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_schadensmeldungen', to='chafon_api.benutzer')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schadensmeldungen', to='chafon_api.ware')),
            ],
            options={
                'verbose_name_plural': 'Schadensmeldungen',
                'ordering': ['-erstellt_am'],
                'indexes': [models.Index(fields=['ware', 'quittiert'], name='chafon_api__ware_id_bb9b11_idx'), models.Index(fields=['ausleihe'], name='chafon_api__ausleih_8a48d7_idx'), models.Index(fields=['erstellt_am'], name='chafon_api__erstell_a0892d_idx')],
            },
        ),
    ]
