# Generated by Django 5.2.10 on 2026-03-19 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chafon_api', '0011_add_schadensmeldung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemeinstellung',
            options={'ordering': ['schluessel'], 'verbose_name_plural': 'System-Einstellungen'},
        ),
        migrations.AddField(
            model_name='kategorieverbleibregel',
            name='maximale_leihdauer_tage',
            field=models.PositiveIntegerField(blank=True, help_text='Maximale Ausleihdauer in Tagen. Leer lassen für unbegrenzt.', null=True, verbose_name='Max. Leihdauer (Tage)'),
        ),
        migrations.AlterField(
            model_name='systemeinstellung',
            name='geaendert_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geaenderte_einstellungen', to='chafon_api.benutzer'),
        ),
        migrations.DeleteModel(
            name='AusleiheGenehmigung',
        ),
    ]
